name: tri_switcher
description: "Introducing Tri_Switcher: A sleek Flutter package with left, center, and right states for effortless UI navigation and toggling."
version: 0.0.4
repository: "https://github.com/dev-zayn/triSwitcher"

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.6"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter: